server:
  port: 8004
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://panda:panda123@localhost:8001/eureka/ #配置注册中心地址
