server:
  port: 8003 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
eureka:
  instance:
    hostname: local2 #指定主机地址
  client:
    serviceUrl:
      defaultZone: http://local1:8002/eureka/
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）